version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mongodb

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - python_app

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data: